$axure.loadCurrentPage({
  "url":"登陆界面.html",
  "generationDate":new Date(1413779867080.1),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"4ba8ba68e3de48dd871a5a3cdf569501",
    "type":"Axure:Page",
    "name":"登陆界面",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e54ed6946645430fa9fd7bcb0debe673",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":70},
            "size":{
              "width":470,
              "height":290}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"646ea01758a14fe782014d2511cb99a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":140,
                  "y":70},
                "size":{
                  "width":470,
                  "height":290}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.jpg"}},
{
          "id":"2f83a8247f574dbd9baf33056eaf036d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000CC,
              "opacity":1},
            "location":{
              "x":217,
              "y":144},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e73318c44894256aaed09fdc56adceb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000CC,
                  "opacity":1},
                "location":{
                  "x":217,
                  "y":144},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"49370da438e14778b325ac4c56980eb7",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":144},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"ede3305320fb48c0a354771060cda04f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000CC,
              "opacity":1},
            "location":{
              "x":235,
              "y":190},
            "size":{
              "width":55,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e4065b786d543d4b0401497acb93a53",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000CC,
                  "opacity":1},
                "location":{
                  "x":235,
                  "y":190},
                "size":{
                  "width":55,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f0c28aafaf7e4eea9e0e933d3d9a8329",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":190},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"c4f48bc3d9614515b91892ffc5e87dac",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000CC,
              "opacity":1},
            "location":{
              "x":217,
              "y":238},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"233f5e696b9541f383ddeb42e30c1a29",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000CC,
                  "opacity":1},
                "location":{
                  "x":217,
                  "y":238},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7a4c7688b41a423799dc64dfd5916d1f",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":238},
            "size":{
              "width":70,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"a7842d6164b64e99b3d779134e59c154",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":410,
              "y":300},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Home",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"17e46aa4d8504955b718cf7f8a1b4dfc",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":250,
              "y":300},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Home",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "e54ed6946645430fa9fd7bcb0debe673":{
      "scriptId":"u0"},
    "646ea01758a14fe782014d2511cb99a9":{
      "scriptId":"u1"},
    "2f83a8247f574dbd9baf33056eaf036d":{
      "scriptId":"u2"},
    "6e73318c44894256aaed09fdc56adceb":{
      "scriptId":"u3"},
    "49370da438e14778b325ac4c56980eb7":{
      "scriptId":"u4"},
    "ede3305320fb48c0a354771060cda04f":{
      "scriptId":"u5"},
    "8e4065b786d543d4b0401497acb93a53":{
      "scriptId":"u6"},
    "f0c28aafaf7e4eea9e0e933d3d9a8329":{
      "scriptId":"u7"},
    "c4f48bc3d9614515b91892ffc5e87dac":{
      "scriptId":"u8"},
    "233f5e696b9541f383ddeb42e30c1a29":{
      "scriptId":"u9"},
    "7a4c7688b41a423799dc64dfd5916d1f":{
      "scriptId":"u10"},
    "a7842d6164b64e99b3d779134e59c154":{
      "scriptId":"u11"},
    "17e46aa4d8504955b718cf7f8a1b4dfc":{
      "scriptId":"u12"}}});