$axure.loadCurrentPage({
  "url":"发起交流的页面.html",
  "generationDate":new Date(1414718782039.23),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"888c8794e68c473cb4ee2d20243d7ec7",
    "type":"Axure:Page",
    "name":"发起交流的页面",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b8e8b461266a4bc993cffda4037c400b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":33,
              "y":25},
            "size":{
              "width":740,
              "height":455}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b65799f75f447bf8cf2146c33174b20",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":33,
                  "y":25},
                "size":{
                  "width":740,
                  "height":455}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/从这里开始/u0.jpg"}},
{
          "id":"f2f55ddaeead431e982ca361e88ec4b2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":33,
              "y":65},
            "size":{
              "width":740,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0a07f5473e04b7da345c6e0c3da3019",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":33,
                  "y":65},
                "size":{
                  "width":740,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/从这里开始/u2.jpg"}},
{
          "id":"281b7679d558428e9a56c323ccdacbf6",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":290,
              "y":65},
            "size":{
              "width":100,
              "height":40}},
          "adaptiveStyles":{
}},
{
          "id":"5aa3d56b3554483389455998057555da",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":90,
              "y":75},
            "size":{
              "width":80,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ee4cb4bce26436ca7f456b16e950b94",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":90,
                  "y":75},
                "size":{
                  "width":80,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 从这里开始",
                      "target":{
                        "targetType":"page",
                        "url":"从这里开始.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"afce63e772f3408bb6fe1e88d37a9bd4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":190,
              "y":75},
            "size":{
              "width":80,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90133869a8ae4ca08724e96094e61717",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":190,
                  "y":75},
                "size":{
                  "width":80,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a0f7decf95b345b7a530688540a7ac09",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":413,
              "y":75},
            "size":{
              "width":80,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f091059e3194b0aaac444de6f0dcc10",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":413,
                  "y":75},
                "size":{
                  "width":80,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3e711cfd72ae4ba3a9e9cd9e2b885445",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000CC,
              "opacity":1},
            "location":{
              "x":90,
              "y":138},
            "size":{
              "width":280,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba7d8b9352134ee38ebd277761b72a77",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000CC,
                  "opacity":1},
                "location":{
                  "x":90,
                  "y":138},
                "size":{
                  "width":280,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9c1b5066a8e547f6b3e684679f81924c",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":170},
            "size":{
              "width":540,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"1d7e91f67d3f42d5b338f34a092f567c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000CC,
              "opacity":1},
            "location":{
              "x":90,
              "y":218},
            "size":{
              "width":145,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0c2610581e8d4aa0886f2d2dbae88dd6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000CC,
                  "opacity":1},
                "location":{
                  "x":90,
                  "y":218},
                "size":{
                  "width":145,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"24786fab464a4422b1671a2d44c426cc",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":255},
            "size":{
              "width":540,
              "height":95}},
          "adaptiveStyles":{
}},
{
          "id":"55e75deb472045d99cae9ca8600e9de0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":255},
            "size":{
              "width":80,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4cf60bf955e5407b93c7e04e58fc0b99",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":255},
                "size":{
                  "width":80,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cebbc165bb79457fb4fdf0789107c79a",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":310,
              "y":350},
            "size":{
              "width":30,
              "height":28}},
          "adaptiveStyles":{
}},
{
          "id":"0bbe0132a6db49f4b058962f76d4cb36",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":530,
              "y":400},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 线下交流",
                      "target":{
                        "targetType":"page",
                        "url":"线下交流.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"eac22aa42a64471faecc866c06821987",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":350},
            "size":{
              "width":200,
              "height":28}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "b8e8b461266a4bc993cffda4037c400b":{
      "scriptId":"u0"},
    "5b65799f75f447bf8cf2146c33174b20":{
      "scriptId":"u1"},
    "f2f55ddaeead431e982ca361e88ec4b2":{
      "scriptId":"u2"},
    "e0a07f5473e04b7da345c6e0c3da3019":{
      "scriptId":"u3"},
    "281b7679d558428e9a56c323ccdacbf6":{
      "scriptId":"u4"},
    "5aa3d56b3554483389455998057555da":{
      "scriptId":"u5"},
    "1ee4cb4bce26436ca7f456b16e950b94":{
      "scriptId":"u6"},
    "afce63e772f3408bb6fe1e88d37a9bd4":{
      "scriptId":"u7"},
    "90133869a8ae4ca08724e96094e61717":{
      "scriptId":"u8"},
    "a0f7decf95b345b7a530688540a7ac09":{
      "scriptId":"u9"},
    "6f091059e3194b0aaac444de6f0dcc10":{
      "scriptId":"u10"},
    "3e711cfd72ae4ba3a9e9cd9e2b885445":{
      "scriptId":"u11"},
    "ba7d8b9352134ee38ebd277761b72a77":{
      "scriptId":"u12"},
    "9c1b5066a8e547f6b3e684679f81924c":{
      "scriptId":"u13"},
    "1d7e91f67d3f42d5b338f34a092f567c":{
      "scriptId":"u14"},
    "0c2610581e8d4aa0886f2d2dbae88dd6":{
      "scriptId":"u15"},
    "24786fab464a4422b1671a2d44c426cc":{
      "scriptId":"u16"},
    "55e75deb472045d99cae9ca8600e9de0":{
      "scriptId":"u17"},
    "4cf60bf955e5407b93c7e04e58fc0b99":{
      "scriptId":"u18"},
    "cebbc165bb79457fb4fdf0789107c79a":{
      "scriptId":"u19"},
    "0bbe0132a6db49f4b058962f76d4cb36":{
      "scriptId":"u20"},
    "eac22aa42a64471faecc866c06821987":{
      "scriptId":"u21"}}});