$axure.loadCurrentPage({
  "url":"任务中心.html",
  "generationDate":new Date(1413779867166.11),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"ba92a034964a4d25aebd72e2da613325",
    "type":"Axure:Page",
    "name":"任务中心",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"3c9899b14ac443f389090330d1a6ef08",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":49,
              "y":43},
            "size":{
              "width":740,
              "height":587}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5738472ea43a422bb55e69f7cecf5dc1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":49,
                  "y":43},
                "size":{
                  "width":740,
                  "height":587}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.jpg"}},
{
          "id":"584a28e163824cb786a85df7d1b2b537",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":70},
            "size":{
              "width":180,
              "height":530}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be0c1321739a41bc9a12f8e07fa9bcef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":70},
                "size":{
                  "width":180,
                  "height":530}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u13.jpeg"}},
{
          "id":"980e49ee1afd4bf3a93f45da1e33fc79",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":80},
            "size":{
              "width":110,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a146cab6ca2456cb709733c4595b59e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":80},
                "size":{
                  "width":110,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u16.png"}},
{
          "id":"d3c986b3f1e84a668d93bab5bd62b4ca",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":94,
              "y":180},
            "size":{
              "width":141,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1fa869dac84a4fd58912f6a51b1ced9a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "location":{
                  "x":94,
                  "y":180},
                "size":{
                  "width":141,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"20ef7658f905454c9a30080e08c0ba58",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":83,
              "y":214},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9322387ce325424e91cf25944e228da3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":83,
                  "y":214},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2ac4ed2e9be545438968b22321b4cef9",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":214},
            "size":{
              "width":80,
              "height":16}},
          "adaptiveStyles":{
}},
{
          "id":"e96ea0a636c941c48fff68ad562dd77b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":214},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"91d5777d6c95452f9d597232c765f0cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":120,
                  "y":214},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u2.jpg"}},
{
          "id":"8aa859f872f34875814bb5ecdac7b220",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":206,
              "y":214},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c5b67f949a143ce91776b0671ee9a7a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":206,
                  "y":214},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a710074bc4024a018e7bad4d9f0a2eea",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":114,
              "y":260},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce94245ddf8a4e3a8aa7067d6b7b9e24",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":114,
                  "y":260},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0f8c25301f8c40c2998a7b1cd90fedb2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":114,
              "y":300},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce7bc6514d3e4b90a07880a8d85059b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":114,
                  "y":300},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a6d45a6b8dce415297c5a31e24887c78",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":114,
              "y":340},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ad3078cb84c49ee8da4d0c13013c73b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":114,
                  "y":340},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"77ad201f615444f6a7341b1e6236e1a0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":114,
              "y":380},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db1830e561234d549e8ffbfd4689121d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":114,
                  "y":380},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3932547e689a4b489085e3900eabe10b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":114,
              "y":418},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"adb222ae3b164964a0ee4c56e0893658",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":114,
                  "y":418},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"25b3694498ed4e08aa4ea29cfcfe7595",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":114,
              "y":458},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"63f124dc1b85464ea96c2e6b2ab16787",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":114,
                  "y":458},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"af4fc3d7e1f74b4cb1b6e3041de5db3a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":114,
              "y":498},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b3e33affc43849e9b3de28c358a8881f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":114,
                  "y":498},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fee1baae13874901a41e957c4a6f9bb6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":114,
              "y":538},
            "size":{
              "width":55,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c325ad51b0f4f2b813f1c78d365256b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":114,
                  "y":538},
                "size":{
                  "width":55,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f8e8420284f0434b8f78378897701edb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":114,
              "y":570},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"039c55d52287445fb4a397aea3181286",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":114,
                  "y":570},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 实名认证",
                      "target":{
                        "targetType":"page",
                        "url":"实名认证.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"00b1b8f1abe6444389cf03f5e16c87e9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":80},
            "size":{
              "width":520,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2cae6e70310a4c448a20bbfa818a6e11",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":260,
                  "y":80},
                "size":{
                  "width":520,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u2.jpg"}},
{
          "id":"a12c0812d4ee45ddb48dc74d374717c9",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":80},
            "size":{
              "width":100,
              "height":40}},
          "adaptiveStyles":{
}},
{
          "id":"abb2babdbfcb4c328551c8a8f79e3d12",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":420,
              "y":90},
            "size":{
              "width":90,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"26f60c71c05a4201ac5875b62d5b9987",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":420,
                  "y":90},
                "size":{
                  "width":90,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9c8ae0a23f1141cca21abcf714cd810e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":530,
              "y":90},
            "size":{
              "width":80,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1710a2fec2884927ac944d2b9ace8eff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":530,
                  "y":90},
                "size":{
                  "width":80,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"93476f0d7b974f0385c27b5d47c66de0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":600,
              "y":90},
            "size":{
              "width":130,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27496224214a428aa8fd1e412fde2b43",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":600,
                  "y":90},
                "size":{
                  "width":130,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "3c9899b14ac443f389090330d1a6ef08":{
      "scriptId":"u0"},
    "5738472ea43a422bb55e69f7cecf5dc1":{
      "scriptId":"u1"},
    "584a28e163824cb786a85df7d1b2b537":{
      "scriptId":"u2"},
    "be0c1321739a41bc9a12f8e07fa9bcef":{
      "scriptId":"u3"},
    "980e49ee1afd4bf3a93f45da1e33fc79":{
      "scriptId":"u4"},
    "9a146cab6ca2456cb709733c4595b59e":{
      "scriptId":"u5"},
    "d3c986b3f1e84a668d93bab5bd62b4ca":{
      "scriptId":"u6"},
    "1fa869dac84a4fd58912f6a51b1ced9a":{
      "scriptId":"u7"},
    "20ef7658f905454c9a30080e08c0ba58":{
      "scriptId":"u8"},
    "9322387ce325424e91cf25944e228da3":{
      "scriptId":"u9"},
    "2ac4ed2e9be545438968b22321b4cef9":{
      "scriptId":"u10"},
    "e96ea0a636c941c48fff68ad562dd77b":{
      "scriptId":"u11"},
    "91d5777d6c95452f9d597232c765f0cb":{
      "scriptId":"u12"},
    "8aa859f872f34875814bb5ecdac7b220":{
      "scriptId":"u13"},
    "1c5b67f949a143ce91776b0671ee9a7a":{
      "scriptId":"u14"},
    "a710074bc4024a018e7bad4d9f0a2eea":{
      "scriptId":"u15"},
    "ce94245ddf8a4e3a8aa7067d6b7b9e24":{
      "scriptId":"u16"},
    "0f8c25301f8c40c2998a7b1cd90fedb2":{
      "scriptId":"u17"},
    "ce7bc6514d3e4b90a07880a8d85059b8":{
      "scriptId":"u18"},
    "a6d45a6b8dce415297c5a31e24887c78":{
      "scriptId":"u19"},
    "3ad3078cb84c49ee8da4d0c13013c73b":{
      "scriptId":"u20"},
    "77ad201f615444f6a7341b1e6236e1a0":{
      "scriptId":"u21"},
    "db1830e561234d549e8ffbfd4689121d":{
      "scriptId":"u22"},
    "3932547e689a4b489085e3900eabe10b":{
      "scriptId":"u23"},
    "adb222ae3b164964a0ee4c56e0893658":{
      "scriptId":"u24"},
    "25b3694498ed4e08aa4ea29cfcfe7595":{
      "scriptId":"u25"},
    "63f124dc1b85464ea96c2e6b2ab16787":{
      "scriptId":"u26"},
    "af4fc3d7e1f74b4cb1b6e3041de5db3a":{
      "scriptId":"u27"},
    "b3e33affc43849e9b3de28c358a8881f":{
      "scriptId":"u28"},
    "fee1baae13874901a41e957c4a6f9bb6":{
      "scriptId":"u29"},
    "2c325ad51b0f4f2b813f1c78d365256b":{
      "scriptId":"u30"},
    "f8e8420284f0434b8f78378897701edb":{
      "scriptId":"u31"},
    "039c55d52287445fb4a397aea3181286":{
      "scriptId":"u32"},
    "00b1b8f1abe6444389cf03f5e16c87e9":{
      "scriptId":"u33"},
    "2cae6e70310a4c448a20bbfa818a6e11":{
      "scriptId":"u34"},
    "a12c0812d4ee45ddb48dc74d374717c9":{
      "scriptId":"u35"},
    "abb2babdbfcb4c328551c8a8f79e3d12":{
      "scriptId":"u36"},
    "26f60c71c05a4201ac5875b62d5b9987":{
      "scriptId":"u37"},
    "9c8ae0a23f1141cca21abcf714cd810e":{
      "scriptId":"u38"},
    "1710a2fec2884927ac944d2b9ace8eff":{
      "scriptId":"u39"},
    "93476f0d7b974f0385c27b5d47c66de0":{
      "scriptId":"u40"},
    "27496224214a428aa8fd1e412fde2b43":{
      "scriptId":"u41"}}});