$axure.loadCurrentPage({
  "url":"注册界面.html",
  "generationDate":new Date(1414718781648.21),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"651192e70d9d4c3a97432804c41e3abe",
    "type":"Axure:Page",
    "name":"注册界面",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e54ed6946645430fa9fd7bcb0debe673",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":70},
            "size":{
              "width":470,
              "height":290}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"646ea01758a14fe782014d2511cb99a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":140,
                  "y":70},
                "size":{
                  "width":470,
                  "height":290}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/从这里开始/u0.jpg"}},
{
          "id":"2f83a8247f574dbd9baf33056eaf036d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000CC,
              "opacity":1},
            "location":{
              "x":217,
              "y":112},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e73318c44894256aaed09fdc56adceb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000CC,
                  "opacity":1},
                "location":{
                  "x":217,
                  "y":112},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"49370da438e14778b325ac4c56980eb7",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":112},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"ede3305320fb48c0a354771060cda04f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000CC,
              "opacity":1},
            "location":{
              "x":235,
              "y":158},
            "size":{
              "width":55,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e4065b786d543d4b0401497acb93a53",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000CC,
                  "opacity":1},
                "location":{
                  "x":235,
                  "y":158},
                "size":{
                  "width":55,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f0c28aafaf7e4eea9e0e933d3d9a8329",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":158},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"a7842d6164b64e99b3d779134e59c154",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":410,
              "y":310},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 从这里开始",
                      "target":{
                        "targetType":"page",
                        "url":"从这里开始.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"17e46aa4d8504955b718cf7f8a1b4dfc",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":240,
              "y":310},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 从这里开始",
                      "target":{
                        "targetType":"page",
                        "url":"从这里开始.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"b970e90114bb41a9b13c5a2849e0a71e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000CC,
              "opacity":1},
            "location":{
              "x":199,
              "y":198},
            "size":{
              "width":91,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f457c73f1d74c979855cf5ba96941e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000CC,
                  "opacity":1},
                "location":{
                  "x":199,
                  "y":198},
                "size":{
                  "width":91,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"53420af43c7c4d7abf0c89de235b361c",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":198},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"e1ed54d358414ca294a92cfebb45ac91",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000CC,
              "opacity":1},
            "location":{
              "x":217,
              "y":240},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1043bd028de749f49e9b98b5d8a2e663",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000CC,
                  "opacity":1},
                "location":{
                  "x":217,
                  "y":240},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fc78f3f6c5264b52b89d8f54def4df09",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":240},
            "size":{
              "width":80,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"dc013e38da4c4dd4bc23a4c17a43b2ee",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":211,
              "y":277},
            "size":{
              "width":100,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"528c4ccf07ae47f08f37140c401ebf2e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":211,
                  "y":277},
                "size":{
                  "width":100,
                  "height":19}},
              "adaptiveStyles":{
}}]},
{
          "id":"7adb55a689774f57afb21d37787f46c8",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":277},
            "size":{
              "width":90,
              "height":23}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "e54ed6946645430fa9fd7bcb0debe673":{
      "scriptId":"u0"},
    "646ea01758a14fe782014d2511cb99a9":{
      "scriptId":"u1"},
    "2f83a8247f574dbd9baf33056eaf036d":{
      "scriptId":"u2"},
    "6e73318c44894256aaed09fdc56adceb":{
      "scriptId":"u3"},
    "49370da438e14778b325ac4c56980eb7":{
      "scriptId":"u4"},
    "ede3305320fb48c0a354771060cda04f":{
      "scriptId":"u5"},
    "8e4065b786d543d4b0401497acb93a53":{
      "scriptId":"u6"},
    "f0c28aafaf7e4eea9e0e933d3d9a8329":{
      "scriptId":"u7"},
    "a7842d6164b64e99b3d779134e59c154":{
      "scriptId":"u8"},
    "17e46aa4d8504955b718cf7f8a1b4dfc":{
      "scriptId":"u9"},
    "b970e90114bb41a9b13c5a2849e0a71e":{
      "scriptId":"u10"},
    "7f457c73f1d74c979855cf5ba96941e0":{
      "scriptId":"u11"},
    "53420af43c7c4d7abf0c89de235b361c":{
      "scriptId":"u12"},
    "e1ed54d358414ca294a92cfebb45ac91":{
      "scriptId":"u13"},
    "1043bd028de749f49e9b98b5d8a2e663":{
      "scriptId":"u14"},
    "fc78f3f6c5264b52b89d8f54def4df09":{
      "scriptId":"u15"},
    "dc013e38da4c4dd4bc23a4c17a43b2ee":{
      "scriptId":"u16"},
    "528c4ccf07ae47f08f37140c401ebf2e":{
      "scriptId":"u17"},
    "7adb55a689774f57afb21d37787f46c8":{
      "scriptId":"u18"}}});