$axure.loadCurrentPage({
  "url":"资源预览界面.html",
  "generationDate":new Date(1413779867483.12),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"09f7f8b632fe49e984878535f0a97f6f",
    "type":"Axure:Page",
    "name":"资源预览界面",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e54ed6946645430fa9fd7bcb0debe673",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":70},
            "size":{
              "width":470,
              "height":290}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"646ea01758a14fe782014d2511cb99a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":140,
                  "y":70},
                "size":{
                  "width":470,
                  "height":290}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.jpg"}},
{
          "id":"2f83a8247f574dbd9baf33056eaf036d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000CC,
              "opacity":1},
            "location":{
              "x":187,
              "y":80},
            "size":{
              "width":343,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e73318c44894256aaed09fdc56adceb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000CC,
                  "opacity":1},
                "location":{
                  "x":187,
                  "y":80},
                "size":{
                  "width":343,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a7842d6164b64e99b3d779134e59c154",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":410,
              "y":315},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 在线文档",
                      "target":{
                        "targetType":"page",
                        "url":"在线文档.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"17e46aa4d8504955b718cf7f8a1b4dfc",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":210,
              "y":315},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 查看资源界面",
                      "target":{
                        "targetType":"page",
                        "url":"查看资源界面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"122a6503a72a4865b356f573727ad51f",
          "label":"",
          "type":"inlineFrame",
          "styleType":"inlineFrame",
          "visible":true,
          "style":{
            "location":{
              "x":187,
              "y":120},
            "size":{
              "width":393,
              "height":180}},
          "adaptiveStyles":{
}},
{
          "id":"40fb382dc5c245fa922285cf11f0a03a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":187,
              "y":120},
            "size":{
              "width":373,
              "height":160}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8508d74bb2e14e1e8ad706fe88736508",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":187,
                  "y":120},
                "size":{
                  "width":373,
                  "height":160}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "e54ed6946645430fa9fd7bcb0debe673":{
      "scriptId":"u0"},
    "646ea01758a14fe782014d2511cb99a9":{
      "scriptId":"u1"},
    "2f83a8247f574dbd9baf33056eaf036d":{
      "scriptId":"u2"},
    "6e73318c44894256aaed09fdc56adceb":{
      "scriptId":"u3"},
    "a7842d6164b64e99b3d779134e59c154":{
      "scriptId":"u4"},
    "17e46aa4d8504955b718cf7f8a1b4dfc":{
      "scriptId":"u5"},
    "122a6503a72a4865b356f573727ad51f":{
      "scriptId":"u6"},
    "40fb382dc5c245fa922285cf11f0a03a":{
      "scriptId":"u7"},
    "8508d74bb2e14e1e8ad706fe88736508":{
      "scriptId":"u8"}}});